### ISSUE TITLE
put into chrome web store

### ISSUE THREAD

**Issue by evdama** [RedHatter/svelte-devtools#1]
this is great! thanks much for your work!

in order to boost adoption and use, are you planning on putting in chome's web store, much like the myriad of other dev tools such as react dev tools etc.?

**Comment by RedHatter** [comment]
Eventually. Hopefully soon. I'm writing a pull request for svelte to eliminate the need for instrumenting the code bundle. I would like to have that merged before I put it on the various web stores.

I would consider the current approach to be more of a developer preview. It works **most** of the time but the approach includes hard limits and will fail at times especially in Chrome.

**Comment by evdama** [comment]
I see. Understood. Makes sense. Just thought because widespread adoption has a lot to do with ease of 'installing' it... people are lazy so... :)

**Comment by QuantumInformation** [comment]
Any feedback on your PR?
