### ISSUE TITLE
Doesn't use Dev Tools theme

### ISSUE THREAD

**Issue by SteveALee** [RedHatter/svelte-devtools#10]
I installed a fresh copy of Developer Edition of Firefox and installed svelte-devtools.

All the F12 panels are using a dark theme (black background) except svelte-tools which is light

Svelte-devtools should follow whichever theme is in use.

**Comment by RedHatter** [comment]
Duplicate of #5 and #9

**Comment by RedHatter** [comment]
The newly released version 1.1.0 supports dark mode
