### ISSUE TITLE
information about how to enable dev mode

### ISSUE THREAD

**Issue by evdama** [RedHatter/svelte-devtools#11]
I think it would be rather helpful for lots of people to add a line to the docs how to enable dev mode when they start from the default svelte or sapper templates. Otherwise they would install this extension an it wouldn't work just because `dev: false` by default.

**Comment by scottdotjs** [comment]
Yeah, it took me finding this issue to be aware of `dev: true`, and then it's barely mentioned in the `svelte-loader` docs - so I had to scratch my head a bit before understanding that you need to specify it in that loader's options in your Webpack config. 

Thanks for this tool!

**Comment by Svein-Tore** [comment]
Why is this issue closed? I don't know where to set dev:true. Where to add dev:true?  That is the question of this issue, and it is not completed @RedHatter

**Comment by eye-wave** [comment]
> Why is this issue closed? I don't know where to set dev:true. Where to add dev:true? That is the question of this issue, and it is not completed @RedHatter

in compiler options. either in a vite plugin or in svelte.config file
