### ISSUE TITLE
Unserializable data breaks app

### ISSUE THREAD

**Issue by selevt** [RedHatter/svelte-devtools#12]
When using [crayon router](https://github.com/alshdavid/crayon) the app doesn't load anymore when using the devtools.

Error on firefox:
```
DataCloneError: The object could not be cloned.
```

Error on chrome (referenced symbol can also be something else):
```
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Symbol(Symbol.species) could not be cloned.
```

Example on codesandbox (try to load without and with devtools):
https://lk9m0.csb.app/

Source:
https://codesandbox.io/s/recursing-cori-lk9m0

**Comment by RedHatter** [comment]
Fixed in 81ae8d6caafd6cb8e8f464dac2625e10f443bd75
