### ISSUE TITLE
privilegedContent.js error

### ISSUE THREAD

**Issue by hack2root** [RedHatter/svelte-devtools#13]
privilegedContent.js:1 Uncaught SyntaxError: Identifier 'tag' has already been declared

**Comment by RedHatter** [comment]
Thank you for the report.

What browser are you using?

Can you provide more details on how you got the error?

**Comment by KieranHolroyd** [comment]
https://gist.github.com/KieranHolroyd/48085b89c283e0f5c80f8afd86031ba8

this is the file

and this is the error, i got this error too. i'm using laravel & inertiajs
privilegedContent.js:1 Uncaught SyntaxError: Identifier 'tag' has already been declared
    at VM2690 privilegedContent.js:1

**Comment by KieranHolroyd** [comment]
i was thinking it might have something to do with the dynamic importing of scripts?

**Comment by burningTyger** [comment]
I'm still getting this error in current chome on linux when running a sapper app

**Comment by RedHatter** [comment]
@burningTyger What version of svelte-devtools are you using? The fix for this is on master but hasn't been released yet (working on that right now).

**Comment by RedHatter** [comment]
Never mind. I was able to reproduce using the sapper template. I've pushed a fix that should prevent any possibility of this issue popping up again.

**Comment by burningTyger** [comment]
Thank you, will test this asap :)

**Comment by burningTyger** [comment]
Works as expected now. Great extension to FF and Chrome. Thank you very much, highly appreciated.
