### ISSUE TITLE
Lights up on sites not using svelte

### ISSUE THREAD

**Issue by wpatter6** [RedHatter/svelte-devtools#17]
Is it possible to have the badge grayscale on sites that aren't using svelte, and red when a site is using it (even in production mode -- similar to vue and react's devtools)?  It'd be a nice addition to be able to see what sites are actually using svelte

**Comment by RedHatter** [comment]
svelte-devtools doesn't watch any pages until you open it. This means it can't know if the page uses svelte beforehand. In other words, this is something that could be done but would have performance issues.
