### ISSUE TITLE
Feature request - Edge support!

### ISSUE THREAD

**Issue by mikemaccana** [RedHatter/svelte-devtools#19]
**Describe the bug**
Edge is a non-adware Chromium browser that supports Chrome extensions. However the extension doesn't connect on latest svelte (3.15.0), `dev: true`, using Edge 80.0.334.4 

**To Reproduce**
Install Svelte DevTools from Chrome App store onto Edge

**Expected behavior**
Svelte DevTools to connect.

**Comment by RedHatter** [comment]
Unfortunately while Edge does support webextensions in general many of the APIs that make svelte-devtools work are not available. For example see [devtools.panels.create()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/create)

**Comment by RedHatter** [comment]
After looking through your issue again I realize I miss-understood. You're not talking about the normal edge but the new experimental chromium based edge. Being essentially the same as chrome it should indeed support svelte-devtools. I checked, and svelte-devtools 1.2.0 does run fine.

There was an issue with svelte 3.14 breaking sevelte-devtools. Maybe that was what you experienced? In any case the latest version does work on edge chromium.
