### ISSUE TITLE
Page near-blank after loading Svelte DevTools when using yrv router

### ISSUE THREAD

**Issue by mikemaccana** [RedHatter/svelte-devtools#20]
**Describe the bug**

**To Reproduce**
Using Chrome 78.0.3904.108. 

Before Svelte DevTools connecting: 

![image](https://user-images.githubusercontent.com/172594/69806299-7ca5ba00-11da-11ea-876f-a2e88b01ef06.png)

After Svelte DevTools connecting: 

![image](https://user-images.githubusercontent.com/172594/69806400-aa8afe80-11da-11ea-8e8c-809cb3b8e3e9.png)

I guess I expected to see the page and the content, and the props of each component. But there's just an `<Unknown />` component for the router and that's it. I can't see the page.

As routers are pretty popular (yrv is new, but getting more popular) it'd be useful for them to work with Svelte DevTools.

**Comment by RedHatter** [comment]
An internal changed in Svelte 3.14 broke devtools. The recently released svelte-devtools 1.2.0 (approved in the chrome store today) should fix this issue.
