### ISSUE TITLE
Doesn't work on iframes

### ISSUE THREAD

**Issue by umanghome** [RedHatter/svelte-devtools#21]
**Describe the bug**
If the Svelte app is running within an iframe, the extension fails to detect it.

**To Reproduce**
1. Create an app, and open it from an iframe.

**Expected behavior**
The app within the iframe should be detected.

**Environment**
 - Browser with version: Chrome 78
- Devtools version: built from master
- Svelte version: 3.15.0

**Comment by umanghome** [comment]
@RedHatter Still doesn't seem to work with a page that's open in an iframe. :/

**Comment by RedHatter** [comment]
It looks to be working for me. Can you give an example of an app that doesn't work?
