### ISSUE TITLE
Devtools appears to disconnect when the URL changes

### ISSUE THREAD

**Issue by Quantumplation** [RedHatter/svelte-devtools#23]
**Describe the bug**
Devtools mount successfully at first, but when [svelte-routing](https://github.com/EmilTholin/svelte-routing), any change in the URL results in the devtools losing contact with svelte and needing a refresh.

**To Reproduce**

1. Clone the [svelte-routing example](https://github.com/EmilTholin/svelte-routing/tree/master/example).
2. Update it to svelte 3.12.1, and modify rollup.config.js to set dev: true
3. `npm run start`, and connect the dev tools to the page
4. Click "About", and observe that the dev tools disconnected.

**Expected behavior**
Devtools stay connected as the url changes

**Environment**
 - Browser with version: Chrome Version 78.0.3904.87 (Official Build) (64-bit)
- Devtools version: 1.2.1, installed from app store
- Svelte version: 3.12.1

**Comment by robindrost** [comment]
I have the same problem in Chrome. Works correctly in Firefox.

**Comment by RedHatter** [comment]
Thank you for the bug report. I apologize for taking so long to get to this... I missed the initial notification.

**Comment by unlocomqx** [comment]
I'm experiencing a disconnect when location hash changes.
For reproduction: https://github.com/unlocomqx/svelte-devtools-bug
