### ISSUE TITLE
question about #anchor

### ISSUE THREAD

**Issue by mvolkmann** [RedHatter/svelte-devtools#25]
What are "anchors"? I see that I can enable and disable showing this from the eyeball menu. When enabled I see lots of lines containing "#anchor" on the left side. They don't seem related to HTML <a> tags. What do they represent? Maybe add this to the README.

**Comment by RedHatter** [comment]
Svelte uses special comment nodes to position and maintain the order of some elements. It's mostly an internal thing (hence why the visibility is disable by default) and there's not much of a reason you would need to know about them.
