### ISSUE TITLE
can't edit state

### ISSUE THREAD

**Issue by mvolkmann** [RedHatter/svelte-devtools#26]
The README says "By selecting one of the nodes in the tree, you can inspect and edit its current state in the panel to the right." This isn't working for me. But I noticed that the state values do not have names, just numbers. I wonder if this is related to recent changes to the way Svelte manages the state in components, storing it in an array. Perhaps svelte-devtools just hasn't been updated to work with the new way to storing state yet.

**Comment by RedHatter** [comment]
Your hunch is right. This is a known issue in svelte 3.16 see sveltejs/svelte#4041 and sveltejs/svelte#3822. This will be an easy fix once the PR is merged.

**Comment by mvolkmann** [comment]
@RedHatter What about the ability to edit state values? As far as I can tell, this still doesn't work. Is that still wanting on a change in Svelte itself?

**Comment by RedHatter** [comment]
I apologize... there was a bug in one of my recent commits causing props not to be cloned. Try the latest version. You can install from Firefox or master. Chrome is still under review.
