### ISSUE TITLE
Which directory is 'dest' directory using sapper

### ISSUE THREAD

**Issue by st-clair-clarke** [RedHatter/svelte-devtools#27]
Your docs state

```
Chrome

    Navigate to chrome://extensions/.
    Turn on developer mode using the 'Developer mode' switch in the upper right hand corner of the page.
    Click 'Load Unpacked' and select the dest directory.

```

I am using sapper (with svelte). Which directory is now dest directory?

**Comment by RedHatter** [comment]
The dest directory inside of the svelte-devtools project not the project you're trying to view. In other words `svelte-devtools/dest`. I hope that clears things up.
