### ISSUE TITLE
Add support for keyboard navigation

### ISSUE THREAD

**Issue by jpaquim** [RedHatter/svelte-devtools#28]
First of all, thank you for all the work on the Devtools, they're looking great and really help with day-to-day work with Svelte.

I just miss something when compared to the regular DOM Devtools, keyboard navigation! Currently, it seems that arrows up/down performs page scrolling, if the content overflows. I think it would make more sense for the arrow keys to behave as when navigating the DOM in the Elements view.

**Comment by RedHatter** [comment]
Hmm, yes, good idea. I'll see if I can find some time to work on this soon.

**Comment by jpaquim** [comment]
@RedHatter major thanks for addressing this 😄 will report back on any bugs I find
