### ISSUE TITLE
Publish in Edge Add-Ons directory

### ISSUE THREAD

**Issue by bdougherty** [RedHatter/svelte-devtools#29]
Not strictly required since you can change a setting in the browser to enable installs from the Chrome store, but it would be more convenient to have it listed in both places.

https://developer.microsoft.com/en-us/microsoft-edge/extensions/

**Comment by damain** [comment]
This would be nice +1

**Comment by RedHatter** [comment]
Submitted and waiting on review.

**Comment by RedHatter** [comment]
Svelte DevTools has failed review on Edge. I'm waiting on a response from support, but I think it's unlikely that the Edge team will except it.

**Comment by johannsa** [comment]
Hi, @RedHatter!
Did they gave you any reasons for the review to fail? Can you share them?
