### ISSUE TITLE
Make svelte devtools respect console zoom?

### ISSUE THREAD

**Issue by jimjones26** [RedHatter/svelte-devtools#33]
I am getting up there in age and I like to make my fonts bigger, however in the Firefox console when I zoom the Svelte tab does not respect the zoom setting and the font remains tiny. Any chance this could be fixed?

**Comment by RedHatter** [comment]
Unfortunately there's no way to get the DevTools zoom level. However I've implemented a partial fix. While the svelte panel is active pressing `ctl+=`, `ctl+-`, and `ctl+0` will control the zoom level. Let me know if you have any other suggestions!

**Comment by freder** [comment]
zooming works but the default font size def. needs to be bigger:

![image](https://user-images.githubusercontent.com/724844/118016878-3bfe1a00-b356-11eb-9057-7f00e053e040.png)
