### ISSUE TITLE
The extension doesn't connects to Svelte (3.12.1)

### ISSUE THREAD

**Issue by brunetton** [RedHatter/svelte-devtools#4]
Steps to reproduce:
- install the extension (from [v2 release](https://github.com/RedHatter/svelte-devtools/releases/tag/v0.2.0))
- clone and install [Sapper Template](https://github.com/sveltejs/sapper-template)
  - `npx degit "sveltejs/sapper-template#rollup" my-app`
  - `npm i`
- run the app
  - `npm run dev`
- navigate to localhost:3000 
- goto Svelte panel
- reload the page
- constat that the panel still says "Refresh the page to connect to svelte."

I tested on Chrome and FIrefox, the result is the same
- In Firefox, there's an error message in console: "=`TypeError: blockId is undefined (privilegedContent.js:291:23)`

Did I missed something ?
Any help would be really welcome ! Thanks

**Comment by RedHatter** [comment]
I believe this is caused by attempting to use an old version of svelte-devtools with the newer svelte. Try the latest release.

**Comment by brunetton** [comment]
Thanks for your answer.
As I said in the first step I installed svelte-devtools from https://github.com/RedHatter/svelte-devtools/releases/tag/v0.2.0. Is this the last version ? I'll try with the version from git repo

**Comment by brunetton** [comment]
I tried to build the extension from master and appart from a `SyntaxError: The requested module 'fs' does not provide an export named 'promises'` that I solved following [this](https://github.com/nodejs/node/issues/21014), I succeded using it.
- in Firefox [installing it as a temporary module](https://developer.mozilla.org/en-US/docs/Tools/about:debugging#Loading_a_temporary_extension), this works :+1: 
- in Chome it complained about not found icons, but this works after removing icons from manifest

So you were right, the issue were a the "v2" release doesn't seems to work well with Svelte 3.12.1. 

Maybe you should publish a new release to match what it's said in README ? 

Thanks

**Comment by cbenz** [comment]
@brunetton I solved the error with promises by using node 12 (`nvm use 12`)

**Comment by RedHatter** [comment]
@brunetton I did publish a new release. [version 1.0.0](https://github.com/RedHatter/svelte-devtools/releases/tag/1.0.0)

**Comment by brunetton** [comment]
@RedHatter thanks ! It works great with Chrome and Firefox 👍
