### ISSUE TITLE
Chrome dev tool dark mode support

### ISSUE THREAD

**Issue by HoraceKeung** [RedHatter/svelte-devtools#9]
![image](https://user-images.githubusercontent.com/6639120/65949219-aab58a80-e433-11e9-98c3-91d61102b861.png)
Thank you for the dev tool, would like to mention that it is hard to read when the browser is in dark mode. Would love to have dark mode support. This is not urgent since it is not a functionality issue, just a "good to have".

For your information, I am on Windows 10, and Chrome's light/dark mode is controlled by changing the Colours settings on Windows.

**Comment by RedHatter** [comment]
Dark mode support was recently added to master. There are a few more changes I would like to make before I release a new version.

**Comment by SteveALee** [comment]
apologies I scan the list but completely missed #9.
